name: lint
on:
  pull_request:
    paths:
      - "**/**/*.go"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - master
    paths:
      - "**/**/*.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m
